version: "3.0"

services:

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    build: ./backend/
    ports:
      - "5555:5555"
    container_name: backend
    depends_on:
      - db

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend